name: "📚 Documentation Update"
description: "Suggest improvements or corrections to documentation"
title: "DOCS:"
labels: [Documentation, Needs Triage]
body:
  - type: textarea
    attributes:
      label: "What documentation needs updating?"
      description: "Please describe the documentation that requires attention."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I'm a GSSoC'24 contributor"
        - label: "I want to work on updating the documentation"
          required: true
