name: First Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hey there👋, Congratulations on creating your first issue with Blogzen. Hope you solve it! This is your first issue."
          pr-message: "Congratulations🎉 on creating your first pull request in Blogzen. This is your first pull request."
